### PR TITLE
Modify README.md

### PR DESCRIPTION
**Pull request by Naturalclar**
modified the explanation for generated Props so that it matches the actual usage

### CODE REVIEW

**Comment by MoOx** [comment]
I am not sure to follow. The prop is actually available only if you use --remove-fill (which remove fill svg attribute so we can inject the prop safely)

**Comment by Naturalclar** [comment]
Sorry, I misunderstood the remove-fill property.

When I tried creating svg for react-native with and without `--remove-fill`, both components seems to have the `fill` property, is that an expected behavior?

- made with `npx react-from-svg assets/svgs src/svgs --with-native`

```
import React from 'react';
import Svg, {
  Circle,
  ClipPath,
  Defs,
  Ellipse,
  ForeignObject,
  G,
  Image,
  Line,
  LinearGradient,
  Marker,
  Mask,
  Path,
  Pattern,
  Polygon,
  Polyline,
  RadialGradient,
  Rect,
  Symbol,
  Text,
  TextPath,
  TSpan as Tspan,
  Use,
} from 'react-native-svg';
export default ({width, height, fill, stroke}) => {
  return (<Svg  viewBox="0 0 56 64" width={width} height={height} fill={fill} stroke={stroke}> <Defs> <Style>.a,.f{fill:none;}.a{stroke:#ddd;stroke-width:2px;}.b{fill:#fa6f6f;}.c{fill:#fff;font-size:17px;font-family:HiraginoSans-W6, Hiragino Sans;letter-spacing:0.05em;}.d{fill:#ddd;}.e{stroke:none;}</Style> </Defs> <G transform="translate(-132 -242)"> <G class="a" transform="translate(132 242)"> <Circle class="e" cx="28" cy="28" r="28"/> <Circle class="f" cx="28" cy="28" r="27"/> </G> <Path class="b" d="M41.447,7.52A23.733,23.733,0,0,1,48,24,24,24,0,1,1,6.506,7.569C19.13,1.651,26.838,15.769,41.447,7.52Z" transform="translate(136 246)"/> <Text class="c" transform="translate(169 277)"> <Tspan x="-17" y="0">高</Tspan> </Text> <Path class="d" d="M5,0l5,9.167H0Z" transform="translate(165 306) rotate(180)"/> </G> </Svg>);
};

```

- made with `npx react-from-svg assets/svgs src/svgs --with-native --remove-fill`

```
import React from 'react';
import Svg, {
  Circle,
  ClipPath,
  Defs,
  Ellipse,
  ForeignObject,
  G,
  Image,
  Line,
  LinearGradient,
  Marker,
  Mask,
  Path,
  Pattern,
  Polygon,
  Polyline,
  RadialGradient,
  Rect,
  Symbol,
  Text,
  TextPath,
  TSpan as Tspan,
  Use,
} from 'react-native-svg';
export default ({width, height, fill, stroke}) => {
  return (<Svg  viewBox="0 0 56 64" width={width} height={height} fill={fill} stroke={stroke}> <Defs> <Style>.a,.f{fill:none;}.a{stroke:#ddd;stroke-width:2px;}.b{fill:#fa6f6f;}.c{fill:#fff;font-size:17px;font-family:HiraginoSans-W6, Hiragino Sans;letter-spacing:0.05em;}.d{fill:#ddd;}.e{stroke:none;}</Style> </Defs> <G transform="translate(-132 -242)"> <G class="a" transform="translate(132 242)"> <Circle class="e" cx="28" cy="28" r="28"/> <Circle class="f" cx="28" cy="28" r="27"/> </G> <Path class="b" d="M41.447,7.52A23.733,23.733,0,0,1,48,24,24,24,0,1,1,6.506,7.569C19.13,1.651,26.838,15.769,41.447,7.52Z" transform="translate(136 246)"/> <Text class="c" transform="translate(169 277)"> <Tspan x="-17" y="0">高</Tspan> </Text> <Path class="d" d="M5,0l5,9.167H0Z" transform="translate(165 306) rotate(180)"/> </G> </Svg>);
};
```

**Comment by MoOx** [comment]
Hum looks like there is a bug :') 

Also just side note but I didn't worked on `<style>` support yet :D

**Comment by MoOx** [comment]
Oh wait ok, fill & stroke are always injected. --remove-fill is to remove fill inside svg children. (same for remove-stroke)). Sometimes when you do a black icon you have the color multiple time on each children...
Maybe I should add better doc about this?

**Comment by MoOx** [comment]
@Naturalclar do you still think we should clarify this?

**Pull request closed without merging**
